---
version: '3.7'
services:

    # Eureka Server / Registry Service
    registry-service:
        build:
            context: ./registry-service
        container_name: registry-service
        restart: always
        ports:
            - "8761:8761"
        environment:
            - SPRING_PROFILES_ACTIVE=registry
            - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
            - EUREKA_CLIENT_FETCH_REGISTRY=false
            - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false
