apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry-service
  name: registry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-service
  strategy: {}
  template:
    metadata:

      labels:
        app: registry-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: 6531503042/registry-service:latest
          name: registry-service
          ports:
            - containerPort: 8761
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry-service
  name: registry-service
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    app: registry-service
status:
  loadBalancer: {}
