# Spring Configuration
spring:
  application:
    name: registry-service
  profiles:
    active: registry

server:
  port: ${PORT:8761}

# Configuration for Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

# Security Configuration
security:
  user:
    name: eureka
    password: password

# Logging Configuration
logging:
  level:
    org.springframework.web: DEBUG
