name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [registry-service, user-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Check if service is complete
        id: check_service
        run: |
          if [ -f "${{ matrix.service }}/completed" ]; then
            echo "Service ${{ matrix.service }} is complete"
            echo "SERVICE_COMPLETE=true" >> $GITHUB_ENV
          else
            echo "Service ${{ matrix.service }} is not complete"
            echo "SERVICE_COMPLETE=false" >> $GITHUB_ENV
          fi

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        if: env.SERVICE_COMPLETE == 'true'

      - name: Build with Maven
        run: mvn clean install -f ${{ matrix.service }}/pom.xml
        if: env.SERVICE_COMPLETE == 'true'

      - name: Package application
        run: mvn package -f ${{ matrix.service }}/pom.xml
        if: env.SERVICE_COMPLETE == 'true'

      - name: List files in target directory
        run: |
          if [ -d "${{ matrix.service }}/target" ]; then
            ls -al ${{ matrix.service }}/target/
          else
            echo "Target directory does not exist"
            exit 1
          fi
        if: env.SERVICE_COMPLETE == 'true'

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.service }}
          path: ${{ matrix.service }}/target/*.jar
        if: env.SERVICE_COMPLETE == 'true'

  build-image-docker:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service: [registry-service, user-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR file artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.service }}
          path: ${{ matrix.service }}/target/
        if: needs.build.outputs.SERVICE_COMPLETE == 'true'

      - name: List files in service directory
        run: ls -al ${{ matrix.service }}/target/
        if: needs.build.outputs.SERVICE_COMPLETE == 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service }}
          dockerfile: ${{ matrix.service }}/Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/microservices-test-${{ matrix.service }}:latest
        if: needs.build.outputs.SERVICE_COMPLETE == 'true'

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service }}
          dockerfile: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/microservices-test-${{ matrix.service }}:latest
        if: needs.build.outputs.SERVICE_COMPLETE == 'true'
