name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install -f registry-service/pom.xml

      - name: Package application
        run: mvn package -f registry-service/pom.xml

      - name: List files in target directory
        run: |
          if [ -d "registry-service/target" ]; then
            ls -al registry-service/target/
          else
            echo "Target directory does not exist"
            exit 1
          fi

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: registry-service-jar
          path: registry-service/target/registry-service-0.0.1-SNAPSHOT.jar
